# Generated by Django 4.2.7 on 2024-07-11 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rsystem", "0005_rename_car_reservation_car_make"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cars",
            options={"ordering": ["make"]},
        ),
        migrations.RenameField(
            model_name="cars",
            old_name="car_make",
            new_name="make",
        ),
    ]
