# Generated by Django 4.2.7 on 2024-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rsystem", "0006_alter_cars_options_rename_car_make_cars_make"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="make_car",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
