# Generated by Django 4.2.7 on 2024-07-18 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rsystem", "0007_reservation_make_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="make_car",
        ),
        migrations.AddField(
            model_name="reservation",
            name="chk_availability",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
