# Generated by Django 4.2.7 on 2024-07-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rsystem", "0008_remove_reservation_make_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.DateField(),
        ),
    ]
