# Generated by Django 4.2.7 on 2024-07-23 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rsystem", "0010_remove_reservation_chk_availability_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["start_date"]},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 24, 3, 5, 59, 500214)
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 24, 3, 5, 59, 500214)
            ),
        ),
    ]
